[project]
name = "sysinner-httplb"
version = "0.11.7"
vendor = "sysinner.com"
homepage = "http://www.sysinner.com"
description = "SysInner HTTP Load Balancer"
groups = ["dev/sys-srv"]

[files]
allow = """README.md
LICENSE"""

[scripts]
build = """mkdir -p {{.buildroot}}/bin
mkdir -p {{.buildroot}}/var/log
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -trimpath -ldflags \"-w -s -X main.version={{.project__version}} -X main.release={{.project__release}}\" -o {{.buildroot}}/bin/sysinner-httplb ./main.go
"""
